# Generated by Django 3.2.5 on 2022-02-22 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataLMS', '0002_remove_issuedbooks_id_alter_issuedbooks_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbooks',
            name='issueID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
